"""align_job_posts_model_with_db

Revision ID: 2bf211e06feb
Revises: d1af7d03df06
Create Date: 2026-06-02 12:52:17.438033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bf211e06feb'
down_revision: Union[str, Sequence[str], None] = 'd1af7d03df06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_posts', sa.Column('material_type', sa.String(), nullable=True))
    op.add_column('job_posts', sa.Column('truck_type', sa.String(), nullable=True))
    op.add_column('job_posts', sa.Column('offered_unit_price', sa.Integer(), nullable=True))
    op.add_column('job_posts', sa.Column('payer_type', sa.String(), nullable=True))
    op.add_column('job_posts', sa.Column('memo', sa.String(), nullable=True))
    op.add_column('job_posts', sa.Column('matched_drop_off_id', sa.Integer(), nullable=True))
    op.alter_column('job_posts', 'drop_off_request_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'job_posts', 'drop_offs', ['matched_drop_off_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job_posts', type_='foreignkey')
    op.alter_column('job_posts', 'drop_off_request_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('job_posts', 'matched_drop_off_id')
    op.drop_column('job_posts', 'memo')
    op.drop_column('job_posts', 'payer_type')
    op.drop_column('job_posts', 'offered_unit_price')
    op.drop_column('job_posts', 'truck_type')
    op.drop_column('job_posts', 'material_type')
    # ### end Alembic commands ###
