"""add_proof_photo_to_dispatch_tickets

Revision ID: 3308b6a8e79f
Revises: 3ccc45aba9bd
Create Date: 2026-06-17 14:35:56.263950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3308b6a8e79f'
down_revision: Union[str, Sequence[str], None] = '3ccc45aba9bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dispatch_tickets', sa.Column('proof_photo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dispatch_tickets', 'proof_photo')
    # ### end Alembic commands ###
