"""add_driver_user_id_unique

Revision ID: 3ccc45aba9bd
Revises: 3790704b30b7
Create Date: 2026-06-05 16:07:14.227239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ccc45aba9bd'
down_revision: Union[str, Sequence[str], None] = '3790704b30b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'drivers', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'drivers', type_='unique')
    # ### end Alembic commands ###
