"""add_geofencing_columns_to_construction_site

Revision ID: 687e49a22fab
Revises: b16246ece042
Create Date: 2026-05-27 14:08:03.624997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '687e49a22fab'
down_revision: Union[str, Sequence[str], None] = 'b16246ece042'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('construction_sites', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('construction_sites', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('construction_sites', sa.Column('geofencing_radius', sa.Float(), nullable=False, server_default='200.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('construction_sites', 'geofencing_radius')
    op.drop_column('construction_sites', 'longitude')
    op.drop_column('construction_sites', 'latitude')
    # ### end Alembic commands ###
