"""add_figma_columns_to_sdui_templates

Revision ID: 6daf85a44ca9
Revises: 2bf211e06feb
Create Date: 2026-06-04 11:10:05.064036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6daf85a44ca9'
down_revision: Union[str, Sequence[str], None] = '2bf211e06feb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sdui_templates', sa.Column('figma_url', sa.String(), nullable=True))
    op.add_column('sdui_templates', sa.Column('figma_node_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sdui_templates', 'figma_node_id')
    op.drop_column('sdui_templates', 'figma_url')
    # ### end Alembic commands ###
