"""expand_drop_off_request_fields

Revision ID: 9c18bfb241ea
Revises: 12d9c83f0f52
Create Date: 2026-05-27 15:09:37.412299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c18bfb241ea'
down_revision: Union[str, Sequence[str], None] = '12d9c83f0f52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. PostgreSQL Enum Types 생성
    truck_type_enum = sa.Enum('T_15', 'T_25', 'T_27', name='trucktype')
    payer_type_enum = sa.Enum('SITE_PAYS', 'DROP_OFF_PAYS', 'FREE', name='payertype')
    payment_method_enum = sa.Enum('MONTHLY', 'DAILY', name='paymentmethod')
    material_type_enum = sa.Enum('GOOD_SOIL', 'MUD_SOIL', 'ROCK', 'MIXED', name='materialtype')
    
    truck_type_enum.create(op.get_bind(), checkfirst=True)
    payer_type_enum.create(op.get_bind(), checkfirst=True)
    payment_method_enum.create(op.get_bind(), checkfirst=True)
    material_type_enum.create(op.get_bind(), checkfirst=True)

    # 2. 컬럼 추가 및 변경
    op.add_column('drop_off_requests', sa.Column('truck_type', truck_type_enum, nullable=False))
    op.add_column('drop_off_requests', sa.Column('target_quantity', sa.Integer(), nullable=False))
    op.add_column('drop_off_requests', sa.Column('current_quantity', sa.Integer(), nullable=False))
    op.add_column('drop_off_requests', sa.Column('payer_type', payer_type_enum, nullable=False))
    op.add_column('drop_off_requests', sa.Column('payment_method', payment_method_enum, nullable=False))
    op.add_column('drop_off_requests', sa.Column('has_washing_facility', sa.Boolean(), nullable=False))
    op.add_column('drop_off_requests', sa.Column('night_work_allowed', sa.Boolean(), nullable=False))
    op.add_column('drop_off_requests', sa.Column('rain_work_allowed', sa.Boolean(), nullable=False))
    op.add_column('drop_off_requests', sa.Column('start_date', sa.DateTime(timezone=True), nullable=False))
    op.add_column('drop_off_requests', sa.Column('end_date', sa.DateTime(timezone=True), nullable=False))
    
    # material_type 컬럼의 타입을 VARCHAR -> Enum으로 캐스팅 변경
    op.execute("ALTER TABLE drop_off_requests ALTER COLUMN material_type TYPE materialtype USING material_type::materialtype")
    
    op.drop_column('drop_off_requests', 'capacity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drop_off_requests', sa.Column('capacity', sa.INTEGER(), autoincrement=False, nullable=False))
    
    # material_type 컬럼 타입을 VARCHAR로 원복
    op.alter_column('drop_off_requests', 'material_type',
               existing_type=sa.Enum('GOOD_SOIL', 'MUD_SOIL', 'ROCK', 'MIXED', name='materialtype'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
               
    op.drop_column('drop_off_requests', 'end_date')
    op.drop_column('drop_off_requests', 'start_date')
    op.drop_column('drop_off_requests', 'rain_work_allowed')
    op.drop_column('drop_off_requests', 'night_work_allowed')
    op.drop_column('drop_off_requests', 'has_washing_facility')
    op.drop_column('drop_off_requests', 'payment_method')
    op.drop_column('drop_off_requests', 'payer_type')
    op.drop_column('drop_off_requests', 'current_quantity')
    op.drop_column('drop_off_requests', 'target_quantity')
    op.drop_column('drop_off_requests', 'truck_type')
    
    # Enum Types 삭제
    sa.Enum(name='trucktype').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='payertype').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='paymentmethod').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='materialtype').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
