"""add_site_key_to_construction_sites

Revision ID: b16246ece042
Revises: 6ce8c6929bd5
Create Date: 2026-05-27 13:34:19.045504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b16246ece042'
down_revision: Union[str, Sequence[str], None] = '6ce8c6929bd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('construction_sites', sa.Column('site_key', sa.String(), nullable=True))
    op.create_index(op.f('ix_construction_sites_site_key'), 'construction_sites', ['site_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_construction_sites_site_key'), table_name='construction_sites')
    op.drop_column('construction_sites', 'site_key')
    # ### end Alembic commands ###
