"""introduce_hybrid_common_code

Revision ID: d1af7d03df06
Revises: 9c18bfb241ea
Create Date: 2026-05-27 15:17:12.422798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd1af7d03df06'
down_revision: Union[str, Sequence[str], None] = '9c18bfb241ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('common_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_code', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('code_name', sa.String(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_code', 'code', name='_group_code_code_uc')
    )
    op.create_index(op.f('ix_common_codes_code'), 'common_codes', ['code'], unique=False)
    op.create_index(op.f('ix_common_codes_group_code'), 'common_codes', ['group_code'], unique=False)
    op.create_index(op.f('ix_common_codes_id'), 'common_codes', ['id'], unique=False)
    
    # Enum 타입을 VARCHAR(String)으로 변환
    op.alter_column('drop_off_requests', 'material_type',
               existing_type=postgresql.ENUM('GOOD_SOIL', 'MUD_SOIL', 'ROCK', 'MIXED', name='materialtype'),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('drop_off_requests', 'truck_type',
               existing_type=postgresql.ENUM('T_15', 'T_25', 'T_27', name='trucktype'),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('drop_off_requests', 'payer_type',
               existing_type=postgresql.ENUM('SITE_PAYS', 'DROP_OFF_PAYS', 'FREE', name='payertype'),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('drop_off_requests', 'payment_method',
               existing_type=postgresql.ENUM('MONTHLY', 'DAILY', name='paymentmethod'),
               type_=sa.String(),
               existing_nullable=False)

    # 이전 Enum 타입 청소(Drop)
    op.execute("DROP TYPE IF EXISTS trucktype CASCADE")
    op.execute("DROP TYPE IF EXISTS payertype CASCADE")
    op.execute("DROP TYPE IF EXISTS paymentmethod CASCADE")
    op.execute("DROP TYPE IF EXISTS materialtype CASCADE")

    # --- 초기 공통 코드 13종 자동 적재 (Data Seeding) ---
    op.execute("""
        INSERT INTO common_codes (group_code, code, code_name, display_order, is_active, created_at, updated_at) VALUES
        ('MATERIAL_TYPE', 'GOOD_SOIL', '양질토', 1, true, now(), now()),
        ('MATERIAL_TYPE', 'MUD_SOIL', '뻘흙', 2, true, now(), now()),
        ('MATERIAL_TYPE', 'ROCK', '암버럭', 3, true, now(), now()),
        ('MATERIAL_TYPE', 'MIXED', '혼합', 4, true, now(), now()),
        
        ('TRUCK_TYPE', 'T_15', '15톤', 1, true, now(), now()),
        ('TRUCK_TYPE', 'T_25', '25톤', 2, true, now(), now()),
        ('TRUCK_TYPE', 'T_27', '27톤', 3, true, now(), now()),
        
        ('PAYER_TYPE', 'SITE_PAYS', '현장 지불', 1, true, now(), now()),
        ('PAYER_TYPE', 'DROP_OFF_PAYS', '하차지 지불', 2, true, now(), now()),
        ('PAYER_TYPE', 'FREE', '무상', 3, true, now(), now()),
        
        ('PAYMENT_METHOD', 'MONTHLY', '월대', 1, true, now(), now()),
        ('PAYMENT_METHOD', 'DAILY', '당일지급', 2, true, now(), now())
        ON CONFLICT (group_code, code) DO NOTHING;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Enum Types 원복 생성
    op.execute("CREATE TYPE trucktype AS ENUM ('T_15', 'T_25', 'T_27')")
    op.execute("CREATE TYPE payertype AS ENUM ('SITE_PAYS', 'DROP_OFF_PAYS', 'FREE')")
    op.execute("CREATE TYPE paymentmethod AS ENUM ('MONTHLY', 'DAILY')")
    op.execute("CREATE TYPE materialtype AS ENUM ('GOOD_SOIL', 'MUD_SOIL', 'ROCK', 'MIXED')")

    op.alter_column('drop_off_requests', 'payment_method',
               existing_type=sa.String(),
               type_=postgresql.ENUM('MONTHLY', 'DAILY', name='paymentmethod'),
               existing_nullable=False,
               postgresql_using="payment_method::paymentmethod")
    op.alter_column('drop_off_requests', 'payer_type',
               existing_type=sa.String(),
               type_=postgresql.ENUM('SITE_PAYS', 'DROP_OFF_PAYS', 'FREE', name='payertype'),
               existing_nullable=False,
               postgresql_using="payer_type::payertype")
    op.alter_column('drop_off_requests', 'truck_type',
               existing_type=sa.String(),
               type_=postgresql.ENUM('T_15', 'T_25', 'T_27', name='trucktype'),
               existing_nullable=False,
               postgresql_using="truck_type::trucktype")
    op.alter_column('drop_off_requests', 'material_type',
               existing_type=sa.String(),
               type_=postgresql.ENUM('GOOD_SOIL', 'MUD_SOIL', 'ROCK', 'MIXED', name='materialtype'),
               existing_nullable=False,
               postgresql_using="material_type::materialtype")
    
    op.drop_index(op.f('ix_common_codes_id'), table_name='common_codes')
    op.drop_index(op.f('ix_common_codes_group_code'), table_name='common_codes')
    op.drop_index(op.f('ix_common_codes_code'), table_name='common_codes')
    op.drop_table('common_codes')
    # ### end Alembic commands ###
